### ISSUE TITLE
Minimum Boost version?

### ISSUE THREAD

**Issue by jwmelto** [CyberRadio/gr-cyberradio#2]
Building gr-CyberRadio on CentOS 7, CMake fails with a Boost minimum version. The last available package for CentOS 7 is 1.53. GNU-Radio is built for CentOS 7 with 1.53. Does gr-CyberRadio **really** need 1.55?

**Comment by bsmith-epiq** [comment]
#4 Should resolve 3.8 and boost issues. Please check your build environment.

**Comment by jwmelto** [comment]
Confirmed.
