### ISSUE TITLE
Update for current GNU Radio

### ISSUE THREAD

**Issue by jwmelto** [CyberRadio/gr-cyberradio#9]
GNU Radio is currently at version 3.10, with 3.11 coming soon.

I think it was 3.9 where the python binding was changed from swig to pybind11. This of course means all OOT blocks need to be ported, but there is a handy porting tool.

gr-cyberradio needs to be updated to support the latest GNU Radio

**Comment by bsmith-epiq** [comment]
I've been working on this in the background here. I have at least the vita-rx block ported correctly and functioning. I'll see if I can push a branch up today for you. Are there other blocks you may be using that would be beneficial as well? We are looking to strip down gr-CyberRadio to a smaller subset and move somethings that got "thrown" in out of it.

**Comment by bsmith-epiq** [comment]
I just pushed my current development of 3.10 to [maint-3.10](https://github.com/CyberRadio/gr-cyberradio/tree/maint-3.10)

**Comment by jwmelto** [comment]
I'm just starting my 3.10 port as well. I'm looking to start using GRC more, and I'm going to refactor our radio setup. 

One complication of the GNU Radio paradigm is that there are some commands that are global in scope ("fun"); some that affect multiple streams, and some that are unique to a single stream. Multiple outputs at different frequencies (or from different antennas) isn't something their model anticipates.

**Comment by bsmith-epiq** [comment]
If you are looking more into GRC, make sure to utilize the Vita Udp RX block, the other vita rx is a non-GRC block. I'm looking into sharing all the code except for the constructor in a further release. 
As for GNURadio handling our type of data, yes we've had to try and work around their model that seems to only expect a 1-to-1 relationship. I can always provide some example GRC files that we utilize here for debugging. But, given our plethora of radios and various nuances on setting each up. We do have some things that aren't "perfect" in our DDC/Tuner control blocks.

**Comment by jwmelto** [comment]
There is a move in GNU Radio towards [SoapySDR](https://github.com/pothosware/SoapySDR/wiki). I don't know enough yet to know if it's a good fit, or if the impedance mismatch will continue. I'll let you know what I find.

**Comment by bsmith-epiq** [comment]
well, if so.... I actually have integrated our radio into there as well. I should push that somewhere...

**Comment by wkazubski** [comment]
In branch maint-3.10 the  version number defined in CmakeLists.txt was decreased from 2.0.0 to 1.0.0.0. This may cause problems while upodating the software with package managers (like apt or rpm) on Linux. Please bump VERSION_MAJOR, defined in line 45 of gr-DyberRadio/CmakeLists.txt, back  to 2 (or more)..

**Comment by bsmith-epiq** [comment]
> In branch maint-3.10 the version number defined in CmakeLists.txt was decreased from 2.0.0 to 1.0.0.0. This may cause problems while upodating the software with package manager. Please bump VERSION_MAJOR, defined in line 45 of gr-DyberRadio/CmakeLists.txt, back to 2 (or more)..

Fixed. 3.0.0.0 is now the CMake version information for the module.
